export enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  ACCESS_TOKEN_NOT_VALID = 'Access token not valid',
}
